version: '3.9'

services:
  db:
    image: mariadb
    container_name: dbMariaDB
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - "/bkp1/pruebas:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=Huixtepec295
      - MYSQL_PASSWORD=Huixtepec295
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=adminnc

  cloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
#    command: apache-foreground
    ports:
      - 80:80
    volumes:
      - "/bkp1/Nextcloud:/var/www/html"
    environment:
      - MYSQL_PASSWORD=Huixtepec295
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=adminnc
      - MYSQL_HOST=dbMariaDB
      - NEXTCLOUD_ADMIN_USER=framos
      - NEXTCLOUD_ADMIN_PASSWORD=framos11
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.encoremsi.com
      #SMTP_HOST (no configurado de forma predeterminada): el nombre de host del servidor SMTP.
      - SMTP_HOST=smtp.zoho.com
      #SMTP_SECURE(vacío de forma predeterminada): configúrelo sslpara usar SSL o tlspara usar STARTTLS.
      - SMTP_SECURE=ssl
      #SMTP_PORT(predeterminado: 465para SSL y 25para conexiones no seguras): puerto opcional para la conexión SMTP. Úselo 587para un puerto alternativo para STARTTLS.
      - SMTP_PORT=465
      #SMTP_AUTHTYPE(predeterminado:): LOGINel método utilizado para la autenticación. Úselo PLAINsi no se requiere autenticación.
      - SMTP_AUTHTYPE=LOGIN
      #SMTP_NAME (vacío de forma predeterminada): el nombre de usuario para la autenticación.
      - SMTP_NAME=admin@encoremsi.com
      #SMTP_PASSWORD (vacío de forma predeterminada): la contraseña para la autenticación.
      - SMTP_PASSWORD=nM70HneKBZjy
      #MAIL_FROM_ADDRESS (no establecido de forma predeterminada): use esta dirección para el campo 'de' en los correos electrónicos enviados por Nextcloud.
      -  MAIL_FROM_ADDRESS=cloud@encoremsi.com
      #MAIL_DOMAIN (no establecido de forma predeterminada): establezca un dominio diferente para los correos electrónicos que el dominio donde está instalado Nextcloud.
      - MAIL_DOMAIN=encoremsi.com
    depends_on:
      - db    

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

