ARG BASEIMAGE=debian:latest
#ARG BASEIMAGE=debian:bullseye-slim
FROM ${BASEIMAGE}

## Archivo de creacion de Imagen Debian 10
#FROM debian
RUN apt-get update
RUN apt-get  install -y iputils-ping  aptitude htop vim \
    nmap nano iproute2 net-tools openssh-server lsb-release

RUN aptitude update

RUN aptitude install -y dialog

RUN aptitude install -y ssh

RUN echo '#Evitar que se desconecta de SSH \n \
	CLIENTALIVEINTERVAL 60 \n \
	CLIENTALIVECOUNTMAX 3' >>/etc/ssh/sshd_config
RUN aptitude install -y ssh


#2.2.Instalar MySQL/MariaDB.
#RUN aptitude install -y mariadb-client mariadb-server

#2.3.Instalar Apache y PHP
#RUN aptitude install -y apache2 libapache2-mod-bw unzip zip \
#    build-essential php php-gd php-phpseclib php-pear php-zip \
#    php-xml php-readline php-mysql php-mbstring php-json php-gd \
#    php-curl php-common php-cli php-cgi php-bz2 libapache2-mod-php \
#    libpq5 php-pgsql php-sqlite3 php-pgsql php-sqlite3 php-imagick \
#    certbot python3-certbot-apache php-tcpdf                                #Se uso el python3 porque python no encontro el paquete
#    certbot python-certbot-apache php-tcpdf                                

#ENV DOMAIN=encoremsi.com
#ENV DNSr=cpe-23-242-120-40.socal.res.rr.com
#ENV IP_EXTERNA=23.242.120.40

# Configuracion para instalar Posrtfix desatendido
#RUN debconf-set-selections <<< "postfix postfix/mailname string $DNSr" \
#    debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

#2.4.Instalar Postfix y Dovecot.
#RUN aptitude install postfix postfix-mysql \
#    dovecot-core dovecot-imapd dovecot-lmtpd dovecot-mysql libsasl2-modules \
#    dovecot-pop3d mysqmail-postfix-logger dovecot-managesieved dovecot-sieve mailutils    


RUN echo ' alias ls="ls $LS_OPTIONS" \n \
 alias ll="ls $LS_OPTIONS -l" \n \
 alias l="ls $LS_OPTIONS -lA" \n \
# Some more alias to avoid making mistakes: \n \
 alias rm="rm -i" \n \
 alias cp="cp -i" \n \
 alias mv="mv -i"' >> ~/.bashrc

#COPY setup.sh /setup.sh
#RUN chmod u+x /setup.sh

## EXPOSE PUERTOS ##
EXPOSE 22/tcp
EXPOSE 25/tcp
EXPOSE 80/tcp
EXPOSE 443/tcp
EXPOSE 465/tcp
EXPOSE 587/tcp
EXPOSE 993/tcp
EXPOSE 995/tcp
EXPOSE 3306/tcp

## VOLUMES ##
#VOLUME [ "/var/lib/mysql", "/prueba/postgresql", "/prueba1/log/postgresql", "/prueba1/lib/postgresql"]

ENTRYPOINT ["/bin/bash"] 
#ENTRYPOINT ["/bin/bash", "--","/setup.sh"] 
